import type {Metadata, Viewport} from "next";
import {Roboto} from "next/font/google";

import {AppRouterCacheProvider} from '@mui/material-nextjs/v15-appRouter';

import {CssBaseline, Stack} from "@mui/material";
import {Footer} from "@/components/global/Footer";
import {ThemeContext} from "@/context/theme";
import config from "@/../public/config.json";

const roboto = Roboto({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Sklep planszowki",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false
};

export default function RootLayout({
                                     children,
                                     navbar,
                                   }: Readonly<{
  children: React.ReactNode;
  navbar: React.ReactNode;
}>) {
  // const res = await fetch(`${process.env.PUBLIC_URL}/config.json`);
  // const config = await res.json();
  const ui = config.mui;

  return (
    <html lang="pl">
    <body className={`${roboto.variable}`} style={{display: 'flex', flexDirection: 'column', minHeight: "100vh"}}>
    <AppRouterCacheProvider>
      <ThemeContext ui={ui}>
        <CssBaseline/>

        {navbar}

        <Stack sx={{flexGrow: 1}}>
          {children}
        </Stack>

        <Footer/>
      </ThemeContext>
    </AppRouterCacheProvider>
    </body>
    </html>
  );
}
