import type {Metadata} from "next";
import {Roboto} from "next/font/google";

import {AppRouterCacheProvider} from '@mui/material-nextjs/v15-appRouter';

import {CssBaseline, Stack} from "@mui/material";
import {Navbar} from "@/components/global/Navbar";
import {Footer} from "@/components/global/Footer";
import theme from "@/theme";
import {ThemeProvider} from "@mui/material/styles";

const roboto = Roboto({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Sklep planszowki",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
    <body className={`${roboto.variable}`} style={{display: 'flex', flexDirection: 'column', minHeight: "100vh"}}>
    <AppRouterCacheProvider>
      <ThemeProvider theme={theme}>
        <CssBaseline/>

        <Navbar/>

        <Stack sx={{flexGrow: 1}}>
          {children}
        </Stack>

        <Footer/>
      </ThemeProvider>
    </AppRouterCacheProvider>
    </body>
    </html>
  );
}
